quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres.ametyohxtrlgkxqxlypr
quarkus.datasource.password=zshS2VDutsXLPt3X
quarkus.datasource.jdbc.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require
quarkus.datasource.jdbc.max-size=16
quarkus.hibernate-orm.database.generation=update

smallrye.jwt.sign.key-location=privateKey.pem
smallrye.jwt.sign.algorithm=RS256

mp.jwt.verify.public-key-location=publicKey.pem
mp.jwt.verify.issuer=https://localhost:8080/

quarkus.native.resources.includes=publicKey.pem,privateKey.pem